language: node_js
node_js:
  - "11.4.0"

addons:
  chrome: stable
  apt:
    packages:
      - software-properties-common

jobs:
  include:
    - stage: run e2e tests
      script:
        - npm i && npm test
